version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    REPOSITORY_URI: <your-ecr-uri>

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo Build started
      - docker build -t ecs-demo-app .
      - docker tag ecs-demo-app:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Pushing image...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"app-container","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
